package com.nova.mobile.command

enum class BuiltInIntent {
    CALL_CONTACT,
    OPEN_APP,
    PLAY_YOUTUBE,
    PLAY_SPOTIFY,
    SET_VOLUME,
    SET_BRIGHTNESS,
    FLASHLIGHT_ON,
    FLASHLIGHT_OFF,
    SEND_SMS,
    OPEN_CAMERA,
    TAKE_PHOTO,
    OPEN_SETTINGS,
    OPEN_MAPS,
    SET_ALARM,
    SET_TIMER,
    SHOW_NOTIFICATIONS,
    READ_NOTIFICATIONS,
    OPEN_BROWSER,
    SEARCH_GOOGLE,
    OPEN_GALLERY,
    COPY_TEXT,
    PASTE_TEXT,
    DEVICE_STATUS,
    BATTERY_STATUS,
    UNKNOWN
}
