"""Memory Category and Event enums."""

from enum import Enum


class MemoryCategory(str, Enum):
    FAVORITE_CONTACT = "FAVORITE_CONTACT"
    FAVORITE_APP = "FAVORITE_APP"
    PREFERRED_MUSIC_APP = "PREFERRED_MUSIC_APP"
    PREFERRED_BROWSER = "PREFERRED_BROWSER"
    PREFERRED_MAPS_APP = "PREFERRED_MAPS_APP"
    PREFERRED_CAMERA_MODE = "PREFERRED_CAMERA_MODE"
    PREFERRED_BRIGHTNESS = "PREFERRED_BRIGHTNESS"
    PREFERRED_VOLUME = "PREFERRED_VOLUME"
    PREFERRED_LANGUAGE = "PREFERRED_LANGUAGE"
    FREQUENT_COMMAND = "FREQUENT_COMMAND"
    RECENT_COMMAND = "RECENT_COMMAND"
    TRUSTED_DEVICE = "TRUSTED_DEVICE"
    KNOWN_WIFI = "KNOWN_WIFI"
    DAILY_ROUTINE = "DAILY_ROUTINE"
    REMINDER_PREFERENCE = "REMINDER_PREFERENCE"
    CALENDAR_PREFERENCE = "CALENDAR_PREFERENCE"
    USER_PREFERENCE = "USER_PREFERENCE"


class MemoryEvent(str, Enum):
    MEMORY_CREATED = "MemoryCreated"
    MEMORY_UPDATED = "MemoryUpdated"
    MEMORY_DELETED = "MemoryDeleted"
    MEMORY_SYNCHRONIZED = "MemorySynchronized"
    MEMORY_IMPORT_COMPLETED = "MemoryImportCompleted"
    MEMORY_EXPORT_COMPLETED = "MemoryExportCompleted"
    MEMORY_CLEARED = "MemoryCleared"
