"""Automation Enums — TriggerType, ConditionType, ActionType, AutomationStatus."""

from enum import Enum


class TriggerType(str, Enum):
    MANUAL = "MANUAL"
    VOICE_COMMAND = "VOICE_COMMAND"
    TIME = "TIME"
    DATE = "DATE"
    DAY_OF_WEEK = "DAY_OF_WEEK"
    BATTERY_LOW = "BATTERY_LOW"
    BATTERY_CHARGING = "BATTERY_CHARGING"
    HEADPHONES_CONNECTED = "HEADPHONES_CONNECTED"
    BLUETOOTH_CONNECTED = "BLUETOOTH_CONNECTED"
    WIFI_CONNECTED = "WIFI_CONNECTED"
    SCREEN_ON = "SCREEN_ON"
    SCREEN_OFF = "SCREEN_OFF"
    NOVA_CORE_CONNECTED = "NOVA_CORE_CONNECTED"
    NOVA_CORE_DISCONNECTED = "NOVA_CORE_DISCONNECTED"
    APP_OPENED = "APP_OPENED"
    LOCATION = "LOCATION"


class ConditionType(str, Enum):
    BATTERY_ABOVE = "BATTERY_ABOVE"
    BATTERY_BELOW = "BATTERY_BELOW"
    WIFI_CONNECTED = "WIFI_CONNECTED"
    CHARGING = "CHARGING"
    HEADPHONES_CONNECTED = "HEADPHONES_CONNECTED"
    TIME_RANGE = "TIME_RANGE"
    SCREEN_LOCKED = "SCREEN_LOCKED"
    SCREEN_UNLOCKED = "SCREEN_UNLOCKED"
    NOVA_CORE_ONLINE = "NOVA_CORE_ONLINE"


class ActionType(str, Enum):
    CALL_CONTACT = "CALL_CONTACT"
    SEND_SMS = "SEND_SMS"
    OPEN_APP = "OPEN_APP"
    PLAY_YOUTUBE = "PLAY_YOUTUBE"
    PLAY_MUSIC = "PLAY_MUSIC"
    FLASHLIGHT_ON = "FLASHLIGHT_ON"
    FLASHLIGHT_OFF = "FLASHLIGHT_OFF"
    SET_BRIGHTNESS = "SET_BRIGHTNESS"
    SET_VOLUME = "SET_VOLUME"
    ENABLE_BLUETOOTH = "ENABLE_BLUETOOTH"
    DISABLE_BLUETOOTH = "DISABLE_BLUETOOTH"
    ENABLE_DND = "ENABLE_DND"
    DISABLE_DND = "DISABLE_DND"
    SET_ALARM = "SET_ALARM"
    SET_TIMER = "SET_TIMER"
    OPEN_CAMERA = "OPEN_CAMERA"
    OPEN_GALLERY = "OPEN_GALLERY"
    COPY_TEXT = "COPY_TEXT"
    SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
    NOVA_CORE_REQUEST = "NOVA_CORE_REQUEST"
    WAIT_SECONDS = "WAIT_SECONDS"


class AutomationStatus(str, Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    RUNNING = "RUNNING"
    ERROR = "ERROR"
    PAUSED = "PAUSED"
