package com.nova.mobile.sync

enum class Platform { ANDROID, NOVA_CORE, TABLET, SMARTWATCH, CLOUD_FUTURE }

enum class DeviceStatus { ONLINE, OFFLINE, CONNECTING, AUTHENTICATED, UNAUTHENTICATED }

enum class ConflictPolicy { NEWEST_WINS, OLDEST_WINS, PHONE_WINS, NOVA_CORE_WINS, USER_CONFIRM }

enum class SyncEvent {
    DEVICE_JOINED,
    DEVICE_LEFT,
    SYNC_STARTED,
    SYNC_COMPLETED,
    SYNC_FAILED,
    SYNC_RESTORED,
    CONFLICT_DETECTED,
    CONFLICT_RESOLVED,
    DEVICE_AUTHENTICATED,
    DEVICE_UNAUTHENTICATED
}

enum class SyncCategory {
    PREFERENCES,
    FAVORITE_CONTACTS,
    FAVORITE_APPS,
    RECENT_COMMANDS,
    ROUTINE_DEFINITIONS,
    TRUSTED_DEVICES,
    SESSION_STATE,
    CONFIGURATION
}
